# Generated by Django 6.0.8 on 2026-08-24 16:26

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='excluded_from_automatic_scheduling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='fairness_history_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='opening_recent_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='employee',
            name='opening_recent_shift_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FiftyFiftyRotationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fifty_fifty_rotation_seeds', to='scheduling.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeRotationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_date', models.DateField(help_text='A Saturday that begins the two-week rotation.')),
                ('office_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('office_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed_saturday_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_rotation_seeds', to='scheduling.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING', 'Generating'), ('GENERATED', 'Generated'), ('NEEDS_REVIEW', 'Needs review'), ('APPROVED', 'Approved'), ('FAILED', 'Failed'), ('SYNCED_TO_SQUARE', 'Synced to Square')], default='DRAFT', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('algorithm_version', models.CharField(default='phase2-deterministic-v1', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedule_runs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('assignment_type', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('ON_CALL', 'On call'), ('FIFTY_FIFTY', '50/50')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('scheduled_paid_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('on_call_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('position_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_templates', to='scheduling.role')),
            ],
            options={
                'ordering': ['position_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(default=datetime.time(18, 30))),
                ('end_time', models.TimeField(default=datetime.time(22, 30))),
                ('venue', models.CharField(default='Theatre Gower', max_length=255)),
                ('expected_guests', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('capacity', models.PositiveSmallIntegerField(default=175)),
                ('capacity_override_reason', models.TextField(blank=True)),
                ('requires_service_staff', models.BooleanField(default=True)),
                ('requires_50_50', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('CALENDAR_IMPORT', 'Calendar import'), ('DEMO', 'Development demo')], default='MANUAL', max_length=32)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time', 'title'],
                'indexes': [models.Index(fields=['date', 'active'], name='show_date_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchedulingWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('SERVER_SHORTAGE', 'Server shortage'), ('BARTENDER_SHORTAGE', 'Bartender shortage'), ('BUSSER_SHORTAGE', 'Busser shortage'), ('FIFTY_FIFTY_SHORTAGE', '50/50 shortage'), ('ON_CALL_SERVER_SHORTAGE', 'On-call server shortage'), ('ON_CALL_BARTENDER_SHORTAGE', 'On-call bartender shortage'), ('UNKNOWN_AVAILABILITY', 'Unknown availability'), ('GUEST_COUNT_DEFAULTED', 'Guest count defaulted'), ('HIGH_GUEST_COUNT_REVIEW', 'High guest count requires review'), ('OFFICE_CONFLICT', 'Office assignment conflict'), ('INSUFFICIENT_FAIRNESS_HISTORY', 'Insufficient fairness history'), ('ROLE_CONFIGURATION_ERROR', 'Role configuration error')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Hard validation error')], default='WARNING', max_length=12)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('schedule_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='scheduling.schedulerun')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_warnings', to='scheduling.show')),
            ],
            options={
                'ordering': ['show__date', 'severity', 'warning_type'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('available', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('availability_type', models.CharField(choices=[('AVAILABLE_ALL_DAY', 'Available all day'), ('AVAILABLE_WINDOW', 'Available during a window'), ('UNAVAILABLE', 'Unavailable'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=32)),
                ('source', models.CharField(default='LOCAL', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_entries', to='scheduling.employee')),
            ],
            options={
                'ordering': ['date', 'employee__display_name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_availability_date')],
            },
        ),
        migrations.CreateModel(
            name='OfficeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('source', models.CharField(default='ROTATION', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_assignments', to='scheduling.employee')),
            ],
            options={
                'ordering': ['date', 'employee__display_name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_office_employee_date')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('ON_CALL', 'On call'), ('FIFTY_FIFTY', '50/50')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('scheduled_paid_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('on_call_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('selection_reason', models.TextField()),
                ('manually_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='scheduling.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='scheduling.role')),
                ('schedule_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.schedulerun')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scheduling.shifttemplate')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='scheduling.show')),
            ],
            options={
                'ordering': ['show__date', 'shift_template__position_order'],
                'constraints': [models.UniqueConstraint(fields=('schedule_run', 'show', 'employee'), name='unique_employee_per_show_run'), models.UniqueConstraint(fields=('schedule_run', 'show', 'shift_template'), name='unique_position_per_show_run')],
            },
        ),
        migrations.CreateModel(
            name='StaffingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_guests', models.PositiveSmallIntegerField(default=1)),
                ('maximum_guests', models.PositiveSmallIntegerField(default=100)),
                ('confirmed_count', models.PositiveSmallIntegerField(default=0)),
                ('on_call_count', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffing_rules', to='scheduling.role')),
            ],
            options={
                'ordering': ['minimum_guests', 'maximum_guests', 'role__name'],
                'constraints': [models.UniqueConstraint(fields=('minimum_guests', 'maximum_guests', 'role', 'effective_from'), name='unique_staffing_rule_period')],
            },
        ),
    ]
