# Generated by Django 6.0.8 on 2026-08-25 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_sandbox_mappings(apps, schema_editor):
    Employee = apps.get_model('scheduling', 'Employee')
    Role = apps.get_model('scheduling', 'Role')
    SquareEmployeeMapping = apps.get_model('scheduling', 'SquareEmployeeMapping')
    SquareRoleMapping = apps.get_model('scheduling', 'SquareRoleMapping')

    for emp in Employee.objects.all():
        sq_id = emp.square_team_member_id or ""
        SquareEmployeeMapping.objects.get_or_create(
            employee=emp,
            environment='sandbox',
            defaults={
                'square_team_member_id': sq_id,
                'status': 'MAPPED' if sq_id else 'UNMAPPED',
            },
        )

    for role in Role.objects.all():
        sq_job_id = role.square_job_id or ""
        SquareRoleMapping.objects.get_or_create(
            role=role,
            environment='sandbox',
            defaults={
                'square_job_id': sq_job_id,
                'square_job_title': role.name if sq_job_id else "",
                'status': 'MAPPED' if sq_job_id else 'UNMAPPED',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_employee_employment_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareLocationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('square_location_id', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['environment', 'location_name'],
                'constraints': [models.UniqueConstraint(fields=('environment', 'square_location_id'), name='unique_environment_square_location')],
            },
        ),
        migrations.CreateModel(
            name='SquareSyncAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PRODUCTION_SYNC_PREVIEWED', 'Production sync previewed'), ('PRODUCTION_PILOT_STARTED', 'Production pilot started'), ('PRODUCTION_PILOT_CREATED', 'Production pilot created'), ('PRODUCTION_PILOT_VERIFIED', 'Production pilot verified'), ('PRODUCTION_SYNC_STARTED', 'Production sync started'), ('PRODUCTION_DRAFT_CREATED', 'Production draft created'), ('PRODUCTION_DRAFT_ALREADY_EXISTS', 'Production draft already exists'), ('PRODUCTION_CONFLICT', 'Production conflict detected'), ('PRODUCTION_DRAFT_FAILED', 'Production draft failed'), ('PRODUCTION_DRAFT_VERIFIED', 'Production draft verified'), ('PRODUCTION_SYNC_COMPLETED', 'Production sync completed')], max_length=50)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', max_length=20)),
                ('square_scheduled_shift_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='square_sync_audit_logs', to='scheduling.scheduleassignment')),
                ('schedule_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='square_sync_audit_logs', to='scheduling.schedulerun')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='square_sync_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SquareEmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('square_team_member_id', models.CharField(blank=True, max_length=100)),
                ('square_given_name', models.CharField(blank=True, max_length=100)),
                ('square_family_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('MAPPED', 'Mapped'), ('UNMAPPED', 'Unmapped'), ('AMBIGUOUS', 'Ambiguous')], default='UNMAPPED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_mappings', to='scheduling.employee')),
            ],
            options={
                'ordering': ['environment', 'employee__display_name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'environment'), name='unique_employee_environment_mapping')],
            },
        ),
        migrations.CreateModel(
            name='SquareRoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('square_job_id', models.CharField(blank=True, max_length=100)),
                ('square_job_title', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('MAPPED', 'Mapped'), ('UNMAPPED', 'Unmapped'), ('AMBIGUOUS', 'Ambiguous')], default='UNMAPPED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_mappings', to='scheduling.role')),
            ],
            options={
                'ordering': ['environment', 'role__name'],
                'constraints': [models.UniqueConstraint(fields=('role', 'environment'), name='unique_role_environment_mapping')],
            },
        ),
        migrations.RunPython(backfill_sandbox_mappings, reverse_code=migrations.RunPython.noop),
    ]

