# Generated by Django 6.0.8 on 2026-08-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_squarelocationmapping_squaresyncauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squareemployeemapping',
            name='confidence_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='squareemployeemapping',
            name='match_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='squareemployeemapping',
            name='potential_square_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='squareemployeemapping',
            name='status',
            field=models.CharField(choices=[('MAPPED_EXACT', 'Mapped (Exact)'), ('MANUAL_REVIEW_REQUIRED', 'Manual Review Required'), ('NOT_FOUND', 'Not Found'), ('INACTIVE', 'Inactive'), ('AMBIGUOUS', 'Ambiguous'), ('MAPPED', 'Mapped'), ('UNMAPPED', 'Unmapped')], default='UNMAPPED', max_length=30),
        ),
        migrations.AlterField(
            model_name='squarerolemapping',
            name='status',
            field=models.CharField(choices=[('MAPPED_EXACT', 'Mapped (Exact)'), ('MANUAL_REVIEW_REQUIRED', 'Manual Review Required'), ('NOT_FOUND', 'Not Found'), ('INACTIVE', 'Inactive'), ('AMBIGUOUS', 'Ambiguous'), ('MAPPED', 'Mapped'), ('UNMAPPED', 'Unmapped')], default='UNMAPPED', max_length=30),
        ),
    ]
