# Generated by Django 6.0.8 on 2026-08-25 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_squareemployeemapping_confidence_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('LIVE_SPIRIT_CALENDAR', 'Live Spirit Show Calendar'), ('LIVE_SQUARE_AVAILABILITY', 'Live Square Availability'), ('LIVE_SQUARE_SHIFTS', 'Live Square Shifts'), ('MANUAL', 'Manual Entry'), ('CSV_IMPORT', 'CSV Import'), ('DEMO', 'Demo Seed'), ('SEED', 'System Seed')], max_length=40)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('environment', models.CharField(default='production', max_length=20)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('is_live', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('raw_payload_json', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-retrieved_at'],
            },
        ),
        migrations.AlterField(
            model_name='schedulerun',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING', 'Generating'), ('GENERATED', 'Generated'), ('NEEDS_REVIEW', 'Needs review'), ('APPROVED', 'Approved'), ('FAILED', 'Failed'), ('SYNCED_TO_SQUARE', 'Synced to Square'), ('SUPERSEDED_SOURCE_DATA', 'Superseded Source Data')], default='DRAFT', max_length=35),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='availability_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_schedule_runs', to='scheduling.sourcesnapshot'),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='calendar_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_schedule_runs', to='scheduling.sourcesnapshot'),
        ),
    ]
