# Generated by Django 6.0.8 on 2026-08-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_sourcesnapshot_alter_schedulerun_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(default='https://spiritofnewfoundland.com/show-calendar/')),
                ('provider', models.CharField(choices=[('API_XHR', 'Structured API/XHR'), ('PLAYWRIGHT', 'Playwright Rendered Browser'), ('FALLBACK_METADATA_ONLY', 'Fallback Metadata Only')], max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('events_received', models.PositiveIntegerField(default=0)),
                ('events_created', models.PositiveIntegerField(default=0)),
                ('events_updated', models.PositiveIntegerField(default=0)),
                ('events_unchanged', models.PositiveIntegerField(default=0)),
                ('events_flagged', models.PositiveIntegerField(default=0)),
                ('rendered_count', models.PositiveIntegerField(default=0)),
                ('extracted_count', models.PositiveIntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial Completeness'), ('FAILED', 'Failed')], default='RUNNING', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
