# Generated by Django 6.0.8 on 2026-08-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_calendarsyncrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareAvailabilitySyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', max_length=20)),
                ('provider', models.CharField(default='STRUCTURED_DASHBOARD_REQUEST', max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employees_requested', models.PositiveIntegerField(default=17)),
                ('employees_found', models.PositiveIntegerField(default=0)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_unchanged', models.PositiveIntegerField(default=0)),
                ('unknown_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial Completeness'), ('FAILED', 'Failed')], default='RUNNING', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
