# Generated by Django 6.0.8 on 2026-08-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_squareavailabilitysyncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerun',
            name='availability_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_runs', to='scheduling.squareavailabilitysyncrun'),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='calendar_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_runs', to='scheduling.calendarsyncrun'),
        ),
    ]
