# Generated by Django 6.0.8 on 2026-08-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_schedulerun_availability_sync_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingwarning',
            name='warning_type',
            field=models.CharField(choices=[('SERVER_SHORTAGE', 'Server shortage'), ('BARTENDER_SHORTAGE', 'Bartender shortage'), ('BUSSER_SHORTAGE', 'Busser shortage'), ('FIFTY_FIFTY_SHORTAGE', '50/50 shortage'), ('ON_CALL_SERVER_SHORTAGE', 'On-call server shortage'), ('ON_CALL_BARTENDER_SHORTAGE', 'On-call bartender shortage'), ('UNKNOWN_AVAILABILITY', 'Unknown availability'), ('GUEST_COUNT_DEFAULTED', 'Guest count defaulted'), ('HIGH_GUEST_COUNT_REVIEW', 'High guest count requires review'), ('OFFICE_CONFLICT', 'Office assignment conflict'), ('INSUFFICIENT_FAIRNESS_HISTORY', 'Insufficient fairness history'), ('ROLE_CONFIGURATION_ERROR', 'Role configuration error'), ('EVENT_STAFFING_REVIEW_REQUIRED', 'Event staffing review required')], max_length=50),
        ),
    ]
