# Generated by Django 6.0.8 on 2026-08-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_alter_schedulingwarning_warning_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeavailability',
            name='unique_employee_availability_date',
        ),
    ]
