# Generated by Django 6.0.8 on 2026-08-25 18:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_remove_employeeavailability_unique_employee_availability_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='squareavailabilitysyncrun',
            name='all_day_combinations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squareavailabilitysyncrun',
            name='available_window_combinations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squareavailabilitysyncrun',
            name='available_window_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squareavailabilitysyncrun',
            name='completeness_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='squareavailabilitysyncrun',
            name='known_employee_date_combinations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squareavailabilitysyncrun',
            name='total_employee_date_combinations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squareavailabilitysyncrun',
            name='unavailable_combinations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squareavailabilitysyncrun',
            name='unknown_employee_date_combinations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedulingwarning',
            name='warning_type',
            field=models.CharField(choices=[('SERVER_SHORTAGE', 'Server shortage'), ('BARTENDER_SHORTAGE', 'Bartender shortage'), ('BUSSER_SHORTAGE', 'Busser shortage'), ('FIFTY_FIFTY_SHORTAGE', '50/50 shortage'), ('ON_CALL_SERVER_SHORTAGE', 'On-call server shortage'), ('ON_CALL_BARTENDER_SHORTAGE', 'On-call bartender shortage'), ('UNKNOWN_AVAILABILITY', 'Unknown availability'), ('GUEST_COUNT_DEFAULTED', 'Guest count defaulted'), ('HIGH_GUEST_COUNT_REVIEW', 'High guest count requires review'), ('OFFICE_CONFLICT', 'Office assignment conflict'), ('INSUFFICIENT_FAIRNESS_HISTORY', 'Insufficient fairness history'), ('ROLE_CONFIGURATION_ERROR', 'Role configuration error'), ('EVENT_STAFFING_REVIEW_REQUIRED', 'Event staffing review required'), ('PRIVATE_EVENT_STAFFING_REVIEW_REQUIRED', 'Private event staffing review required')], max_length=50),
        ),
    ]
