# Generated by Django 6.0.8 on 2026-08-25 18:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_squareavailabilitysyncrun_all_day_combinations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingFairnessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Spirit Fairness Config', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('opportunity_weight', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4)),
                ('hours_weight', models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=4)),
                ('role_opportunity_weight', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4)),
                ('confirmed_shift_weight', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4)),
                ('weekend_weight', models.DecimalField(decimal_places=2, default=Decimal('0.08'), max_digits=4)),
                ('rest_weight', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=4)),
                ('reliability_weight', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=4)),
                ('performance_weight', models.DecimalField(decimal_places=2, default=Decimal('0.04'), max_digits=4)),
                ('role_fit_weight', models.DecimalField(decimal_places=2, default=Decimal('0.03'), max_digits=4)),
                ('on_call_count_weight', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=4)),
                ('on_call_hours_weight', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=4)),
                ('on_call_opportunity_weight', models.DecimalField(decimal_places=2, default=Decimal('0.15'), max_digits=4)),
                ('on_call_confirmed_workload_weight', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4)),
                ('on_call_weekend_weight', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=4)),
                ('on_call_reliability_weight', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=4)),
                ('on_call_role_fit_weight', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=4)),
                ('recent_hours_window_days', models.PositiveIntegerField(default=28)),
                ('confirmed_shift_window_days', models.PositiveIntegerField(default=28)),
                ('on_call_window_days', models.PositiveIntegerField(default=28)),
                ('weekend_window_days', models.PositiveIntegerField(default=56)),
                ('default_reliability', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4)),
                ('default_performance', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-active', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='schedulingwarning',
            name='warning_type',
            field=models.CharField(choices=[('SERVER_SHORTAGE', 'Server shortage'), ('BARTENDER_SHORTAGE', 'Bartender shortage'), ('BUSSER_SHORTAGE', 'Busser shortage'), ('FIFTY_FIFTY_SHORTAGE', '50/50 shortage'), ('ON_CALL_SERVER_SHORTAGE', 'On-call server shortage'), ('ON_CALL_BARTENDER_SHORTAGE', 'On-call bartender shortage'), ('UNKNOWN_AVAILABILITY', 'Unknown availability'), ('GUEST_COUNT_DEFAULTED', 'Guest count defaulted'), ('HIGH_GUEST_COUNT_REVIEW', 'High guest count requires review'), ('OFFICE_CONFLICT', 'Office assignment conflict'), ('INSUFFICIENT_FAIRNESS_HISTORY', 'Insufficient fairness history'), ('ROLE_CONFIGURATION_ERROR', 'Role configuration error'), ('EVENT_STAFFING_REVIEW_REQUIRED', 'Event staffing review required'), ('PRIVATE_EVENT_STAFFING_REVIEW_REQUIRED', 'Private event staffing review required'), ('OPPORTUNITY_IMBALANCE', 'Opportunity distribution imbalance'), ('ON_CALL_IMBALANCE', 'On-call burden imbalance'), ('WEEKEND_IMBALANCE', 'Weekend distribution imbalance'), ('TARGET_HOURS_SHORTFALL', 'Target hours shortfall'), ('EXCESSIVE_CONSECUTIVE_SHIFTS', 'Excessive consecutive shifts'), ('ACTUAL_TIMECARD_HISTORY_NOT_AVAILABLE', 'Actual timecard history not available')], max_length=50),
        ),
        migrations.CreateModel(
            name='EmployeeSchedulingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly target confirmed paid hours for Spirit-only priority staff.', max_digits=6, null=True)),
                ('priority_enabled', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_preference', to='scheduling.employee')),
            ],
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='fairness_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_runs', to='scheduling.schedulingfairnessconfig'),
        ),
        migrations.CreateModel(
            name='SchedulingFairnessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_opportunities', models.PositiveIntegerField(default=0)),
                ('confirmed_opportunities', models.PositiveIntegerField(default=0)),
                ('opportunity_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('recent_actual_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('recent_confirmed_shifts', models.PositiveIntegerField(default=0)),
                ('recent_on_call_assignments', models.PositiveIntegerField(default=0)),
                ('recent_on_call_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('recent_weekend_shifts', models.PositiveIntegerField(default=0)),
                ('consecutive_nights', models.PositiveIntegerField(default=0)),
                ('role_opportunities', models.PositiveIntegerField(default=0)),
                ('target_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('projected_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4)),
                ('performance_score', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4)),
                ('role_fit_score', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4)),
                ('target_hours_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('confirmed_fair_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5)),
                ('on_call_fair_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5)),
                ('selected', models.BooleanField(default=False)),
                ('selection_reason', models.TextField(blank=True)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fairness_snapshots', to='scheduling.employee')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fairness_snapshots', to='scheduling.role')),
                ('schedule_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fairness_snapshots', to='scheduling.schedulerun')),
            ],
            options={
                'ordering': ['schedule_run', 'employee__display_name'],
            },
        ),
    ]
