# Generated by Django 6.0.8 on 2026-08-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_schedulingfairnessconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffingrule',
            name='maximum_guests',
            field=models.PositiveSmallIntegerField(default=80),
        ),
    ]
