# Generated by Django 6.0.8 on 2026-08-26 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_alter_staffingrule_maximum_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeschedulingpreference',
            name='preferred_role',
            field=models.ForeignKey(blank=True, help_text='Where a cross-trained employee would rather work. Applied as a ranking nudge only: it never makes anyone eligible or ineligible, and scarce-skill cover still comes first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferring_employees', to='scheduling.role'),
        ),
    ]
