# Generated by Django 6.0.8 on 2026-08-27 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_alter_squaresyncauditlog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('SQUARE', 'Square'), ('MANUAL', 'Entered here')], default='MANUAL', max_length=20)),
                ('square_time_off_id', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='scheduling.employee')),
            ],
            options={
                'ordering': ('-start_date', 'employee__display_name'),
                'indexes': [models.Index(fields=['start_date', 'end_date', 'status'], name='scheduling__start_d_4e6557_idx')],
            },
        ),
    ]
