# Generated by Django 6.0.8 on 2026-08-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_employeetimeoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetimeoff',
            name='approved_all_day',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employeetimeoff',
            name='approved_partial',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employeetimeoff',
            name='requested_time',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
