# Generated by Django 6.0.8 on 2026-08-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_alter_schedulingwarning_warning_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedulingpreference',
            name='target_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly target confirmed paid hours.', max_digits=6, null=True),
        ),
    ]
