# Generated by Django 6.0.8 on 2026-08-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_alter_employeeschedulingpreference_target_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingwarning',
            name='warning_type',
            field=models.CharField(choices=[('SERVER_SHORTAGE', 'Server shortage'), ('BARTENDER_SHORTAGE', 'Bartender shortage'), ('BUSSER_SHORTAGE', 'Busser shortage'), ('FIFTY_FIFTY_SHORTAGE', '50/50 shortage'), ('ON_CALL_SERVER_SHORTAGE', 'On-call server shortage'), ('ON_CALL_BARTENDER_SHORTAGE', 'On-call bartender shortage'), ('UNKNOWN_AVAILABILITY', 'Unknown availability'), ('GUEST_COUNT_DEFAULTED', 'Guest count defaulted'), ('HIGH_GUEST_COUNT_REVIEW', 'High guest count requires review'), ('OFFICE_CONFLICT', 'Office assignment conflict'), ('INSUFFICIENT_FAIRNESS_HISTORY', 'Insufficient fairness history'), ('SERVER_MANAGER_SHORTAGE', 'Server manager shortage'), ('PARTIAL_SHIFT_COVERAGE', 'Shift only partly covered'), ('ROLE_CONFIGURATION_ERROR', 'Role configuration error'), ('SQUARE_OUT_OF_DATE', 'Square no longer matches this schedule'), ('EVENT_STAFFING_REVIEW_REQUIRED', 'Event staffing review required'), ('PRIVATE_EVENT_STAFFING_REVIEW_REQUIRED', 'Private event staffing review required'), ('OPPORTUNITY_IMBALANCE', 'Opportunity distribution imbalance'), ('ON_CALL_IMBALANCE', 'On-call burden imbalance'), ('WEEKEND_IMBALANCE', 'Weekend distribution imbalance'), ('TARGET_HOURS_SHORTFALL', 'Target hours shortfall'), ('EXCESSIVE_CONSECUTIVE_SHIFTS', 'Excessive consecutive shifts'), ('ACTUAL_TIMECARD_HISTORY_NOT_AVAILABLE', 'Actual timecard history not available')], max_length=50),
        ),
    ]
