# Generated by Django 6.0.8 on 2026-08-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0022_department_employeedepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='on_call_only',
            field=models.BooleanField(default=False, help_text='Qualified to assist in this role but not to hold it alone - never rostered to a confirmed position, only to on-call cover.'),
        ),
    ]
