# Generated by Django 6.0.8 on 2026-09-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0021_overlapping_roster_warning'),
        ('scheduling', '0023_employeerole_on_call_only'),
    ]

    operations = [
    ]
