# Generated by Django 6.0.8 on 2026-09-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0025_alter_schedulingwarning_warning_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squaresyncauditlog',
            name='action_type',
            field=models.CharField(choices=[('PRODUCTION_SYNC_PREVIEWED', 'Production sync previewed'), ('PRODUCTION_PILOT_STARTED', 'Production pilot started'), ('PRODUCTION_PILOT_CREATED', 'Production pilot created'), ('PRODUCTION_PILOT_VERIFIED', 'Production pilot verified'), ('PRODUCTION_SYNC_STARTED', 'Production sync started'), ('PRODUCTION_DRAFT_CREATED', 'Production draft created'), ('PRODUCTION_DRAFT_ALREADY_EXISTS', 'Production draft already exists'), ('PRODUCTION_CONFLICT', 'Production conflict detected'), ('PRODUCTION_DRAFT_FAILED', 'Production draft failed'), ('PRODUCTION_DRAFT_VERIFIED', 'Production draft verified'), ('PRODUCTION_SYNC_COMPLETED', 'Production sync completed'), ('PRODUCTION_DRAFT_DELETED', 'Production draft deleted'), ('PRODUCTION_DRAFT_DELETE_FAILED', 'Production draft delete failed'), ('PRODUCTION_DRAFT_UPDATED', 'Production draft updated'), ('PRODUCTION_DRAFT_UPDATE_FAILED', 'Production draft update failed'), ('PRODUCTION_PUBLISHED_UNCHANGED', 'Published shift left unchanged'), ('PRODUCTION_REMOVED_FROM_SQUARE', 'Production roster removed from Square')], max_length=50),
        ),
    ]
